timmo001/home-panel

README.md, config.template.json, docs/index.md, src/Main.js
Rework header so that entities can be added by users instead of hardcoded
=> Rework header

README.md, docs/index.md
=> Fix docker documentation

src/Components/Main.js
=> :sparkles: add link support

.github/ISSUE_TEMPLATE.md, src/Components/Header.js
Fixes error on bad entities or missing config entries
#26
=> Allow missing or bad header config

docs/docs/themes.md, package.json, src/App.css, src/Components/Header.js, src/Components/InputDialog.js, src/Components/Login.js, src/Components/Main.js, src/Components/MoreInfo.js, src/Components/Root.js, yarn.lock
Fixes multiple layout and sizing issues when dealing with different screen sizes and orientations
#39
=> Responsive fixes

src/Components/Root.js
Stay connected to hass on load and handle any errors connecting and when calling services
#20
=> Stay connected to HASS

src/Components/Main.js, src/Components/Root.js
Enables group toggle of all on or off when clicking of title.
#54
=> Group toggle functionality

package.json, yarn.lock
=> update material-ui to version 3.0.0

.gitlab-ci.yml, Dockerfile
Add architectures to build for and deploy to `armhf`, `aarch64`, `i386` and `amd64`
#16
=> Add architectures

docs/docs/themes.md, src/App.js, src/Components/AlarmPanel.js, src/Components/Main.js, src/Components/Root.js
Adds Alarm control panel support
#43
=> Add support for the alarm component

src/Components/Cards/Group.js
Adds support for groups from home assistant
#106
=> Add support for hass groups

src/Components/Cards/Hass/Hass.js
Adds support for `device_tracker` platform
#132
=> Add support for device_tracker

src/App.js, src/Components/Login.js, src/Components/Main.js, src/Components/Root.js, yarn.lock
Makes Home Assistant optional, so the URL or authentication is optional.
#133
=> Optional Home Assistant Authentication

src/Components/Cards/CardBase.js, src/Components/Cards/Group.js, src/Components/Cards/Hass/Hass.js, src/Components/Cards/Hass/Weather.js, src/Components/Cards/Page.js, src/Components/Main.js, src/Components/Root.js
=> Weather Support

src/App.js, src/Components/Cards/Hass/Climate.js, src/Components/Cards/Hass/Hass.js, src/Components/EditConfig/configExplanations.json, src/Components/EditConfig/defaultConfig.json
=> Climate support

src/Components/Cards/CardBase.js, src/Components/Cards/Group.js, src/Components/Cards/Hass/Hass.js, src/Components/Cards/Hass/Media.js, src/Components/Cards/Page.js, src/Components/Main.js, src/Components/Root.js
Adds support for `media_player` platform for HA.
#114
=> Add media_player support

docker/Dockerfile
Upgrades base images to Alpine 3.9
=> Upgrade to alpine 3.9

package.json, src/Components/EditConfig/RawEditor.js, src/Components/Header.js, src/Components/Main.js, yarn.lock
Adds raw config editor.
Closes #240
=> Raw config editor

package.json, src/Components/EditConfig/EditCard.js, src/Components/EditConfig/Input.js, src/Components/EditConfig/Item.js, yarn.lock
Adds Home Assistant entities to card config with `react-autosuggest`:
Closes #242
=> Add HA entity_id autosuggestions

src/Components/Cards/Hass/Climate.js, src/Components/Cards/Hass/Cover.js, src/Components/Cards/Hass/Hass.js, src/Components/Root.js
Adds support for requested missing Home Assistant domains and fixes a couple of bugs found.
Closes #215 
Closes #260
=> Home Assistant Domain Support

src/Components/Configuration/Config.tsx, src/Components/Configuration/EditCard/EditCard.tsx, src/Components/Configuration/EditGroup.tsx, src/Components/Configuration/Item.tsx, src/Components/Main/Main.tsx, src/Components/Overview/Overview.tsx
=> Edit groups

src/Components/Cards/Base.tsx, src/Components/HomeAssistant/Cards/Climate.tsx, src/Components/HomeAssistant/Cards/Cover.tsx, src/Components/HomeAssistant/Cards/Entity.tsx, src/Components/HomeAssistant/Cards/Fan.tsx, src/Components/HomeAssistant/Cards/Media.tsx, src/Components/HomeAssistant/Cards/State.tsx, src/Components/HomeAssistant/Cards/Toggle.tsx, src/Components/HomeAssistant/Cards/Weather.tsx, src/Components/HomeAssistant/HomeAssistant.tsx
=> HA Entities Support

api/config/config.default.json, src/Components/App.tsx, src/Components/Configuration/Config.tsx, src/Components/Configuration/Configuration.tsx, src/Components/Configuration/Item.tsx, src/Components/Configuration/Section.tsx, src/Components/Drawer/Drawer.tsx, src/Components/Main/Main.tsx, src/Components/Onboarding/Onboarding.tsx, src/Components/Utils/MarkdownText.tsx, src/Components/Utils/parseColors.tsx, src/Components/Utils/parseTheme.tsx
=> Theming support

src/Components/Configuration/EditPage.tsx, src/Components/Overview/Pages.tsx
=> Page editing

src/Components/Overview/Overview.tsx
Tweak size of grid on smaller layouts
Closes #558
=> Tweak grids

src/Components/Configuration/Config.tsx, src/Components/Configuration/EditCard/Entity.tsx, src/Components/HomeAssistant/Cards/State.tsx, src/Components/Visualisations/Chart.tsx
Add chart labels on hover
Closes #548
=> Add chart labels on hover

src/Components/Cards/Base.tsx, src/Components/Configuration/Config.tsx, src/Components/Configuration/EditCard/Base.tsx, src/Components/Configuration/EditCard/Entity.tsx, src/Components/HomeAssistant/Cards/Light.tsx, src/Components/HomeAssistant/Cards/Select.tsx, src/Components/HomeAssistant/Cards/State.tsx, src/Components/HomeAssistant/Cards/Toggle.tsx, src/Components/Overview/Header/Header.tsx
More config for title, icon, state etc.
Closes #502
=> Add config for fonts and icons

src/Components/Cards/Base.tsx, src/Components/Configuration/EditCard/Entity.tsx, src/Components/HomeAssistant/Cards/Climate.tsx, src/Components/HomeAssistant/Cards/Entity.tsx, src/Components/HomeAssistant/Cards/Number.tsx, src/Components/HomeAssistant/HomeAssistant.tsx
Add support for input number, groups and fix user select on climate
Closes #547 
Closes #551
=> Entity Improvements

package.json, src/Components/Cards/Base.tsx, src/Components/Cards/RSS.tsx, src/Components/Configuration/Config.tsx, src/Components/Configuration/EditCard/Base.tsx, src/Components/Configuration/EditCard/RSS.tsx, yarn.lock
Adds RSS Feed cards.
Closes #596
=> Add RSS Feeds

src/Components/Configuration/Config.tsx, src/Components/Configuration/Configuration.tsx, src/Components/Configuration/Item.tsx, src/Components/Main.tsx
Adds a backup and restore option which saves and loads in the config in JSON format.
Closes #501
=> Add Backup and Restore Functionality

src/Components/Main.tsx
Remove quote at end of the backup filename
Closes https://github.com/timmo001/home-panel/issues/608
=> Remove quote at end of the backup filename

api/src/hooks/process-config-update.ts, api/src/hooks/process-config.ts, api/src/hooks/process-controller.ts, api/src/services/config/config.class.ts, api/src/services/controller/controller.class.ts, api/src/services/controller/controller.hooks.ts, api/src/services/controller/controller.service.ts, api/src/services/index.ts, api/test/services/controller.test.ts, src/Components/Cards/Base.tsx, src/Components/Cards/Image.tsx, src/Components/Configuration/EditCard/EditCard.tsx, src/Components/Main.tsx, src/Components/Onboarding.tsx, src/Components/Overview/Overview.tsx, src/Components/Utils/Command.tsx
Adds the controller service to the API which is subscribed to via the UI, which then triggers page changes and image expansion/unexpansion.
Helps with #645
=> Controller

src/Components/Configuration/Config.tsx, src/Components/Configuration/Section.tsx, src/Components/Drawer/Drawer.tsx, src/Components/Main.tsx
Adds drawer types.
Closes #655
=> Drawer Types

src/Components/Cards/Base.tsx, src/Components/Configuration/Config.tsx, src/Components/Configuration/EditCard/Base.tsx
Adds title justify option
Closes #983
=> Add Title Justify Card Config Option

azure-pipelines-ci.yml, azure-pipelines-edge.yml, azure-pipelines-release.yml
=> Fix path for docker

src/Components/HomeAssistant/Cards/Entity.tsx
Fixes toggles for Home Assistant entities. This can be lights, switches, alarms etc. which were not working since the typescript rework
Fixes #1014
=> Fix Home Assistant Toggles

src/Components/HomeAssistant/Cards/State.tsx, src/Components/HomeAssistant/Cards/Weather.tsx, src/Components/HomeAssistant/Utils/Units.tsx
Adds unit of measurement to states. Also reworks weather entity card by removing extra information and adding the icon.
The attributes were causing type errors and are not required, so have been removed
Fixes #995
=> Unit of measurement

frontend/package.json, frontend/src/Components/HomeAssistant/Cards/Weather.tsx, yarn.lock
Updates moment to v2.27.0 and fixes errors
=> ⬆ Update dependency moment to v2.27.0

frontend/src/Components/Cards/Base.tsx, frontend/src/Components/Cards/Overlay.tsx, frontend/src/Components/Configuration/Item.tsx, frontend/src/Components/Drawer/Drawer.tsx, frontend/src/Components/Onboarding.tsx, frontend/src/Components/Overview/Header.tsx
Performance improvements by memoizing, splitting code and making general improvements
=> Performance improvements

frontend/src/Components/Cards/Base.tsx, frontend/src/Components/Configuration/Config.tsx, frontend/src/Components/Configuration/EditCard/Base.tsx, frontend/src/Components/Configuration/EditCard/EditCard.tsx, frontend/src/Components/Configuration/EditCard/Entity.tsx, frontend/src/Components/Configuration/EditCard/EntityAction.tsx, frontend/src/Components/HomeAssistant/Cards/AlarmPanel.tsx, frontend/src/Components/HomeAssistant/Cards/Entity.tsx, frontend/src/Components/HomeAssistant/Cards/Light.tsx
=> Entity Click Action

documentation/docs/setup.md
Hass.io was renamed to Home Assistant.
=> Hass.io was renamed

Dockerfile
Reverts timmo001/home-panel#1436
=> Revert "Dockerfile updates 🎉"

frontend/src/Components/HomeAssistant/HomeAssistant.tsx, frontend/src/Components/HomeAssistant/Utils/Auth.tsx, frontend/src/Components/Main.tsx
> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
=> Fix loop when entering incorrect url

.gitpod.Dockerfile, .gitpod.yml, README.md
> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
=> Add gitpod files
